name: ayat_app
description: "We study how to think like the Noble Quran"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 4.5.1+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ## https://pub.dev/packages/go_router
  go_router: ^17.0.1
  ## https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^9.1.1
  ## https://pub.dev/packages/equatable
  equatable: ^2.0.7
  ## https://github.com/hashirabdulbasheer/noble_quran_flutter_package.git
  noble_quran:
    git:
      url: https://github.com/hashirabdulbasheer/noble_quran_flutter_package.git
      ref: master
  ## https://pub.dev/packages/intl
  intl: ^0.19.0
  ## https://pub.dev/packages/dartz
  dartz: ^0.10.1
  ## https://pub.dev/packages/get_it
  get_it: ^9.2.0
  ## https://pub.dev/packages/injectable
  injectable: ^2.7.1+4
  ## https://pub.dev/packages/dropdown_search
  dropdown_search: ^6.0.2
  ## https://pub.dev/packages/rxdart
  rxdart: ^0.28.0
  ## https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.4
  ## https://pub.dev/packages/scrollable_positioned_list
  scrollable_positioned_list: ^0.3.8
  ## https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.2
  ## https://pub.dev/packages/shimmer
  shimmer: ^3.0.0
  ## https://pub.dev/packages/flex_color_scheme
  flex_color_scheme: ^8.4.0
  ## https://pub.dev/packages/screenshot
  screenshot: ^3.0.0
  ## https://pub.dev/packages/file_saver
  file_saver: ^0.3.1
  ## https://pub.dev/packages/share_plus
  share_plus: ^12.0.1
  ## https://pub.dev/packages/app_links
  app_links: ^7.0.0
  ## https://pub.dev/packages/vibration
  vibration: ^3.1.5
  ## https://pub.dev/packages/http
  http: ^1.6.0
  ## https://pub.dev/packages/carousel_slider
  carousel_slider: ^5.1.1
  ## https://pub.dev/packages/just_audio
  just_audio: ^0.10.5
  ## https://pub.dev/packages/wakelock_plus
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ## https://pub.dev/packages/mockito
  mockito: ^5.6.1
  ## https://pub.dev/packages/build_runner
  build_runner: ^2.10.4
  ## https://pub.dev/packages/bloc_test
  bloc_test: ^10.0.0
  ## https://pub.dev/packages/injectable_generator
  injectable_generator: ^2.9.1
  ## https://pub.dev/packages/golden_toolkit/
  golden_toolkit: ^0.15.0
  ## https://pub.dev/packages/hrk_flutter_test_batteries
  hrk_flutter_test_batteries: ^1.2.0

flutter:
  uses-material-design: true

  fonts:
    # https://fonts.qurancomplex.gov.sa/wp02/en/%D8%AD%D9%81%D8%B5/
    - family: KFGQPC HAFS Uthmanic Script Regular
      fonts:
        - asset: assets/fonts/UthmanicHafs_V22.ttf

    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
